version: '3'

services:
  serve:
    build:
      context: .
    ports:
      - 8080:8080
    volumes:
      - ./:/www
      - /www/build
      - /www/node_modules
      - /www/generator/node_modules
    entrypoint: >
      sh -ce "
        npm run build;
        concurrently -k 'nodemon --delay 100ms --exec \"npm run build\" --ignore ./build/ --ext js,json,ejs,md,css,scss' 'live-server --port=8080 --no-browser ./build/'
      "
