version: '3.6'

services:
  knowledge-base-dev:
    container_name: knowledge-base-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/www/src
    environment:
      NODE_ENV: dev
    ports:
      - 3000:3000
    command: |-
      sh -ce '
        npm run dev;
      '
